### ISSUE TITLE
What would I have to do to deploy for JetsonTX1?

### ISSUE THREAD

**Issue by BoxWizard000000** [Open-RIO/GradleRIO#56]
I'm relatively new to gradle. James, the creator of the tutorial for using GradleRIO directed me here. From what I can tell (if I didn't overlook anything of course), the default build file will not deploy to JetsonTX1/2 correct? What changes would I have to make if I wanted to do this. It's really tedious to code using geddit on the Jetson and I would much prefer to use an IDE and then just cross compile.

This is for vision code so naturally I'd also need to include the opencv libraries. 

If you could just walk me through it, that'd be great. Thank you.

**Comment by JacisNonsense** [comment]
GradleRIO's backing project is [Embedded Tools](https://github.com/JacisNonsense/EmbeddedTools), which provides the interface necessary to deploy to coprocessors. If you have a cross-compiler for the jetson, you can use it like you would with any other coprocessor (e.g. [here](https://github.com/Open-RIO/GradleRIO/tree/master/examples/coprocessor_cpp)), otherwise you will need to copy over your source files (using a fileCollectionArtifact), then run some scripts to compile it onboard the jetson. Those commands will be similar to the process you're currently using to build.
